language: python
notifications:
  email: false
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
before_script:
  - cd src
script:
  - coverage run --source="." manage.py test
after_success:
  - codecov
branches:
  only:
    - master
